### ISSUE TITLE
Use server's IP instead of 127.0.0.1 for client

### ISSUE THREAD

**Issue by joy-allen** [chenweiyu960212/TCP-#1]
When a client runs on the same host as server. The client's IP in server's view is 127.0.0.1. However, the real IP in other clients' view is server's IP. Connecting 127.0.0.1 from other clients will fail if them don't run on the same host as server.

For example:

| Machine | Outer IP | Server's View | Client1's View | Client2's View |
| ----------- | ----------- | -------------------| ------------------- | ------------------- |
| Server    | 192.168.10.1 |                      | 127.0.0.1        | 192.168.10.1 |
| Client1   | 192.168.10.1 | 127.0.0.1       |                       | 192.168.10.1 |
| Client2   | 192.168.20.1 | 192.168.20.1 | 192.168.20.1 |                       |
        
Client1 can't be connected by `127.0.0.1` because server's view is different from Client2's.

Clients are supported to use server's IP when server tell them that the peer is `127.0.0.1`.

By the way, there is no need to set `SO_REUSEADDR` when no conflict exists.

**Comment by weiyu666** [comment]
I'm sorry that I only saw the problem recently because of something at work。

The Tcp link is closed, but there are still some packets in the network that haven't arrived yet;Tcp dictates that all late packets be discarded after shutdown.
A network packet needs to be sent and acknowledged, which is 2MSL.So you need to wait 2MSL after closing.During this time, the original port cannot be used to establish a connection；If you use REUSEADDR, you can immediately establish the connection
